name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build XML To JSON
      run: dotnet build ".\StarCitizen_XML_to_JSON\StarCitizen_XML_To_JSON.csproj" --configuration Release --no-restore

    - name: Build JSON To SQL
      run: dotnet build ".\StarCitizen_JSON_to_SQL\StarCitizen_JSON_To_SQL.csproj" --configuration Release --no-restore

    #- name: Testing XML to JSON
    #  run: dotnet test ".\StarCitizen XML to JSON\StarCitizen XML to JSON.csproj" --no-restore --verbosity normal

    #- name: Testing XML to JSON
    #  run: dotnet test ".\StarCitizen_JSON_To_SQ\StarCitizen_JSON_To_SQ.csproj" --no-restore --verbosity normal
